version: "2"
services:
  node:
    image: "node:22"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    restart: always
    ports: # use if it is necessary to expose the container to the host machine
      - "8082:8080"
    command: "npm run start"

